"""initial schema

Revision ID: cad15f6476cd
Revises: 
Create Date: 2026-03-31 21:28:35.413788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad15f6476cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('input_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_time_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('code_size_bytes', sa.Integer(), nullable=True),
    sa.Column('language_breakdown', sa.Text(), nullable=True),
    sa.CheckConstraint("input_type IN ('url', 'upload', 'paste')", name='ck_scans_input_type'),
    sa.CheckConstraint("status IN ('pending', 'running', 'complete', 'error')", name='ck_scans_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('idx_scans_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_scans_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_user_id'), ['user_id'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('plain_english', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('fix_suggestion', sa.Text(), nullable=False),
    sa.Column('exploit_risk', sa.Integer(), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('owasp_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('security', 'bug', 'performance', 'logic')", name='ck_findings_category'),
    sa.CheckConstraint("severity IN ('critical', 'high', 'medium', 'low')", name='ck_findings_severity'),
    sa.CheckConstraint('exploit_risk >= 0 AND exploit_risk <= 100', name='ck_findings_exploit_risk'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('idx_findings_category', ['category'], unique=False)
        batch_op.create_index('idx_findings_scan_severity', ['scan_id', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('share_uuid', sa.String(length=36), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_is_public', ['is_public'], unique=False)
        batch_op.create_index('idx_reports_scan_id', ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_share_uuid'), ['share_uuid'], unique=True)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_finding_user', ['finding_id', 'user_id'], unique=False)
        batch_op.create_index('idx_comments_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_finding_id'))
        batch_op.drop_index('idx_comments_user_id')
        batch_op.drop_index('idx_comments_finding_user')

    op.drop_table('comments')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_share_uuid'))
        batch_op.drop_index('idx_reports_scan_id')
        batch_op.drop_index('idx_reports_is_public')

    op.drop_table('reports')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_scan_id'))
        batch_op.drop_index('idx_findings_scan_severity')
        batch_op.drop_index('idx_findings_category')

    op.drop_table('findings')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_user_id'))
        batch_op.drop_index(batch_op.f('ix_scans_status'))
        batch_op.drop_index('idx_scans_user_created')
        batch_op.drop_index('idx_scans_created_at')

    op.drop_table('scans')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_users_created_at')

    op.drop_table('users')
    # ### end Alembic commands ###
